import urllib.parse as up

items = [
   "Sticker | Mahjong Zhong",
    "Sticker | Non-Veg",
    "Nova | Sand Dune (Field-Tested)",
    "M4A4 | Evil Daimyo (Field-Tested)",
    "Chroma Case",
    "P250 | Boreal Forest (Field-Tested)",
    "Tec-9 | Ice Cap (Factory New)",
    "MAC-10 | Lapis Gator (Minimal Wear)",
    "AUG | Condemned (Field-Tested)",
    "Chroma 3 Case",
    "MAC-10 | Candy Apple (Factory New)",
    "CZ75-Auto | Polymer (Field-Tested)",
    "MP9 | Bioleak (Factory New)",
    "MAC-10 | Silver (Factory New)",
    "Falchion Case",
    "Sticker | Gambit Esports | Boston 2018",
    "Dual Berettas | Stained (Factory New)",
    "Five-SeveN | Orange Peel (Minimal Wear)",
    "Desert Eagle | Mudder (Field-Tested)",
    "Glock-18 | Bunsen Burner (Field-Tested)",
    "USP-S | Torque (Factory New)",
    "Desert Eagle | Mudder (Minimal Wear)",
    "P2000 | Turf (Field-Tested)",
    "Desert Eagle | Oxide Blaze (Factory New)",
    "Desert Eagle | Urban Rubble (Field-Tested)",
    "MP7 | Urban Hazard (Factory New)",
    "MP7 | Cirrus (Battle-Scarred)",
    "Five-SeveN | Violent Daimyo (Factory New)",
    "MP7 | Asterion (Minimal Wear)",
    "M249 | System Lock (Field-Tested)",
    "AK-47 | Elite Build (Battle-Scarred)",
    "MP9 | Sand Scale (Minimal Wear)",
    "Dual Berettas | Cobalt Quartz (Factory New)",
    "Sticker | chrisJ | Boston 2018",
    "Dual Berettas | Contractor (Field-Tested)",
    "AK-47 | Cartel (Field-Tested)",
    "Dual Berettas | Colony (Battle-Scarred)",
    "AK-47 | Aquamarine Revenge (Battle-Scarred)",
    "AK-47 | Aquamarine Revenge (Factory New)",
    "AK-47 | Aquamarine Revenge (Field-Tested)",
    "AK-47 | Aquamarine Revenge (Minimal Wear)",
    "AK-47 | Aquamarine Revenge (Well-Worn)",
    "AK-47 | Black Laminate (Battle-Scarred)",
    "AK-47 | Black Laminate (Factory New)",
    "AK-47 | Black Laminate (Field-Tested)",
    "AK-47 | Black Laminate (Minimal Wear)",
    "AK-47 | Black Laminate (Well-Worn)",
    "AK-47 | Bloodsport (Factory New)",
    "AK-47 | Bloodsport (Field-Tested)",
    "AK-47 | Bloodsport (Minimal Wear)",
    "AK-47 | Bloodsport (Well-Worn)",
    "AK-47 | Blue Laminate (Factory New)",
    "AK-47 | Blue Laminate (Field-Tested)",
    "AK-47 | Blue Laminate (Minimal Wear)",
    "AK-47 | Blue Laminate (Well-Worn)",
    "AK-47 | Cartel (Battle-Scarred)",
    "AK-47 | Cartel (Factory New)",
    "AK-47 | Cartel (Minimal Wear)",
    "AK-47 | Cartel (Well-Worn)",
    "AK-47 | Case Hardened (Battle-Scarred)",
    "AK-47 | Case Hardened (Factory New)",
    "AK-47 | Case Hardened (Field-Tested)",
    "AK-47 | Case Hardened (Minimal Wear)",
    "AK-47 | Case Hardened (Well-Worn)",
    "AK-47 | Elite Build (Factory New)",
    "AK-47 | Elite Build (Field-Tested)",
    "AK-47 | Elite Build (Minimal Wear)",
    "AK-47 | Elite Build (Well-Worn)",
    "AK-47 | Emerald Pinstripe (Battle-Scarred)",
    "'Blueberries' Buckshot | NSWC SEAL",
    "'The Doctor' Romanov | Sabre",
    "'Two Times' McCoy | TACP Cavalry",
    "'Two Times' McCoy | USAF TACP",
    "2020 RMR Challengers",
    "AK-47 | Aquamarine Revenge (Field-Tested)",
    "AK-47 | Asiimov (Field-Tested)",
    "AK-47 | Frontside Misty (Minimal Wear)",
    "AK-47 | Legion of Anubis (Factory New)",
    "AK-47 | Neon Revolution (Minimal Wear)",
    "AK-47 | Neon Rider (Field-Tested)",
    "AK-47 | Point Disarray (Factory New)",
    "AK-47 | Safari Mesh (Field-Tested)",
    "AK-47 | Safety Net (Factory New)",
    "AK-47 | Uncharted (Minimal Wear)",
    "AK-47 | Uncharted (Well-Worn)",
    "AUG | Aristocrat (Field-Tested)",
    "AUG | Random Access (Field-Tested)",
    "AUG | Storm (Factory New)",
    "AUG | Surveillance (Field-Tested)",
    "AWP | Capillary (Minimal Wear)",
    "AWP | Pit Viper (Minimal Wear)",
    "AWP | Safari Mesh (Battle-Scarred)",
    "Arno The Overgrown | Guerrilla Warfare",
    "Aspirant | Gendarmerie Nationale",
    "AK-47 | Emerald Pinstripe (Factory New)",
    "AK-47 | Emerald Pinstripe (Field-Tested)",
    "AK-47 | Emerald Pinstripe (Minimal Wear)",
    "AK-47 | Emerald Pinstripe (Well-Worn)",

]

items_links = []
def convert_title_to_link(title: str) -> str:
    encoded_title = up.quote_plus(title.replace(' ', '%20'), safe='%20')
    link = 'https://steamcommunity.com/market/listings/730/' + encoded_title
    return link

for item in items: 
    items_links.append(convert_title_to_link(title=item))

proxies = []
for i in range(19000, 19999):
    proxy_data = {
        'user' : 'Lolobroller_17712',
        'pass' : 'yc44zbOJP8',
        'host' : 'ipv4.reproxy.network',
        'port' : i
    }
    proxies.append(proxy_data)